In [1]:
# Adopted from https://medium.com/ai-made-simple/understanding-polynomial-regression-d963ebb7cc6e
import numpy as np
X = np.arange(6).reshape(3, 2)
X

array([[0, 1],
       [2, 3],
       [4, 5]])

The `PolynomialFeatures` is used to generate a new feature matrix consisting of all polynomial combinations of the features with the specified degree. 

In the first line, the `PolynomialFeatures` class is imported from the `sklearn.preprocessing` module. 

For example, if the input data is a 2-dimensional array containing two features `[a, b]`, the output of `PolynomialFeatures` with degree 2 will be a 3-dimensional array containing `[1, a, b, a^2, ab, b^2]`.

The `fit_transform` method is a combination of the `fit` and `transform` methods. The `fit` method computes the necessary transformation based on the input data, and the `transform` method applies this transformation to the data. The result is a new feature matrix that includes the polynomial features of the input data.

In [2]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(2)
poly.fit_transform(X)

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.]])

In [3]:
poly = PolynomialFeatures(3)
poly.fit_transform(X)

array([[  1.,   0.,   1.,   0.,   0.,   1.,   0.,   0.,   0.,   1.],
       [  1.,   2.,   3.,   4.,   6.,   9.,   8.,  12.,  18.,  27.],
       [  1.,   4.,   5.,  16.,  20.,  25.,  64.,  80., 100., 125.]])